apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: collector-service
  name: collector-service
spec:
  ports:
  - name: 8079-8079
    port: 8079
    protocol: TCP
    targetPort: 8079
  selector:
    app: collector-service
  type: ClusterIP
status:
  loadBalancer: {}
