apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: postgres-service
  name: postgres-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgres-service
    spec:
      containers:
      - image: postgres
        name: postgres
        resources: {}
        env:
          - name: POSTGRES_PASSWORD
            value: root
          - name: POSTGRES_DB
            value: postgres
status: {}
