apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: prometheus-service
  name: prometheus-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prometheus-service
    spec:
      containers:
      - image: prom/prometheus
        name: prometheus
        resources: {}
status: {}
