apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rabbimq-service
  name: rabbimq-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbimq-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rabbimq-service
    spec:
      containers:
      - image: rabbitmq
        name: rabbitmq
        resources: {}
    
status: {}
