apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sender-service
  name: sender-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sender-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sender-service
    spec:
      containers:
      - image: smfun12/sender
        name: sender
        resources: {}
        env:
          - name: SPRING_RABBITMQ_HOST
            value: 10.1.0.158
          - name: SPRING_RABBIT_MQ_PORT
            value: '5672'
          - name: SPRING_RABBIT_MQ_USERNAME
            value: guest
          - name: SPRING_RABBIT_MQ_PASSWORD
            value: guest

status: {}
